apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    run: {{ .Values.app.name }}
spec:
  ports:
  - port: {{ .Values.app.ServicePort }}
    protocol: TCP
  selector:
    app: {{ .Values.app.name }}

